static const char * const IV_GRID =
  "#Inventor V2.0 ascii\n"
  "\n"
  "Separator {\n"
  "    PickStyle {\n"
  "	style	UNPICKABLE\n"
  "    }\n"
  "    LightModel {\n"
  "	model	BASE_COLOR\n"
  "    }\n"
  "    NormalBinding {\n"
  "	value	DEFAULT\n"
  "    }\n"
  "    BaseColor {\n"
  "	rgb	0.2 0.2 0.2\n"
  "    }\n"
  "    Array {\n"
  "	numElements1	61\n"
  "	separation1	0.5 0 0\n"
  "	origin	CENTER\n"
  "	Coordinate3 {\n"
  "	    point	[ 0 -15 -1e-05,\n"
  "			      0 15 -1e-05 ]\n"
  "	}\n"
  "	LineSet {\n"
  "	    numVertices	2\n"
  "	}\n"
  "    }\n"
  "    Array {\n"
  "	numElements1	61\n"
  "	separation1	0 0.5 0\n"
  "	origin	CENTER\n"
  "	Coordinate3 {\n"
  "	    point	[ -15 0 -1e-05,\n"
  "			      15 0 -1e-05 ]\n"
  "	}\n"
  "	LineSet {\n"
  "	    numVertices	2\n"
  "	}\n"
  "    }\n"
  "    BaseColor {\n"
  "	rgb	0.4 0 0\n"
  "    }\n"
  "    Coordinate3 {\n"
  "	point	[ -15 0 0,\n"
  "			  15 0 0,\n"
  "			  0 -15 0,\n"
  "			  0 15 0 ]\n"
  "    }\n"
  "    LineSet {\n"
  "	numVertices	[ 2, 2 ]\n"
  "    }\n"
  "}\n";
