#!/bin/sh

#
#  Trivial checking of Buildfiles for kludges
#
#  Usage:  checkBuildfiles directory_name
#  Or:     checkBuildfiles 
#
#  L. Taylor   30 May 2000
#
#


dir_name=$1

if [ "$dir_name" = "" ] 
then
   dir_name="."
fi
   
   
   
echo "----------------------------------------------------- "

find $dir_name \(                      \
                  -name "BuildFile"    \
               \) -exec echo " " \;     \
                  -exec echo "-------------------------------------------------------------------" \;     \
                  -exec echo "Checking file = " {} \;     \
                  -exec grep "/afs" {} \;  \
                  -exec grep "INCLUDE" {} \; \
                  -exec grep "LIBDIR" {} \; 



