#!/bin/sh

#
#  Remove a CVS directory (by CVS deleting all files in it)
#
#  L. Taylor   25 May 2000
#
#
#  Notes:
#  -----
#
#  To delete a whole tree with CVS, you delete all the files inside 
#  and then ask for cvs update/checkout/export with the -P option
#  to force removal of the (now empty) directories.
#
#  You also have to get rid of hidden files. For these, use the 
#  .??*  pattern (dot, then any two characters, then something) 
#  to avoid deleting . and .. (bad idea! even though any sensible 
#  Unix should catch such stupidities)
#
#  -o  denotes OR
#  -a  denotes AND
#
#  The -prune option means that find ignores this tree. It is always true.
#
#  The -print option prints the pattern.  It is always true.
#
#  You must also remove the .xxxx files lying around.






dir_name=$1

if [ "$dir_name" = "" ] 
then
 
   echo " "
   echo "Remove a CVS directory (by CVS deleting all files in it)."
   echo " "
   echo "  Usage:    deleteCVSDirectory directory_name"
   echo " "
   echo "Look into the script for more comments."
   echo " "
   exit
fi
   
echo "----------------------------------------------------- "

find $dir_name \(                            \
           ! \( -name 'CVS*' -prune \)       \
           -a                                \
              \(                             \
                 -name "*"                   \
                 -o                          \
                 -name ".*"                  \
              \)                             \
           -a                                \
           -type f                           \
        \) -exec /bin/rm -i {} \;  -exec cvs delete {} \;


echo " "
echo "----------------------------------------------------- "
echo " "
echo "If you are happy, commit your changes with:"
echo " "
echo "   > cvs ci"
echo " "
echo "N.B. to make the (now empty) directories really disappear:"
echo " "
echo "   > cvs update -P"
echo " "

