#!/bin/sh

## Usage: make-release [-p] [-s] [-b] [-t] [-d] TAG [HOST...]
##  Builds IGUANA version TAG in the current directory on the
##  listed HOSTS.  The setup steps and the build will always
##  be done locally, so you can specify additional hosts for
##  build only if needed.  Options:
##    -p  Skip "scram project", that was already done
##    -s  Skip "scram setup", that was already done
##    -b  Skip build, that was already done
##    -t  Skip tests, that was already done
##    -d  Skip building docs, that was already done
##    -c  Skip directory protection at the end

doproject=true
dosetup=true
dobuild=true
dotests=true
dodocs=true
dochmod=true
avoid=

while [ $# -gt 0 ]; do
  case $1 in
    # Public options to turn off various parts
    -p ) doproject=false avoid="$avoid -p"; shift; continue ;;
    -s ) dosetup=false avoid="$avoid -s"; shift; continue ;;
    -b ) dobuild=false avoid="$avoid -b"; shift; continue ;;
    -t ) dotests=false avoid="$avoid -t"; shift; continue ;;
    -d ) dodocs=false  avoid="$avoid -d"; shift; continue ;;
    -c ) dochmod=false avoid="$avoid -c"; shift; continue ;;

    # Hidden option for multi-host build to turn off docs build
    # on anything but linux
    -D ) case `scram arch` in Linux* ) ;; * ) dodocs=false ;; esac
         shift; continue ;;
  esac
  break
done

$doproject && $dosetup && dosetup=false

if [ $# -lt 1 ]; then
  echo "No tag argument, expeceted IGUANA_X_Y_Z" 1>&2
  exit 1
fi
  
case $1 in IGUANA_*_*_* ) ;; * )
  echo "Badly formed tag argument \`$1', expeceted IGUANA_X_Y_Z" 1>&2
  exit 1 ;;
esac
TAG=$1; shift

if $doproject; then
  # Get configuration
  if [ -z "$CVSROOT" ]; then
    CVSROOT=:pserver:anonymous@cmscvs.cern.ch:/cvs_server/repositories/IGUANA
    export CVSROOT
  fi

  rm -fr config || exit 1
  cvs co -r $TAG config || exit 1

  # Setup release
  scram project file:config/BootStrapFileSRC || exit 1
fi

cd $TAG/src || exit 1

if $dosetup; then
  scram setup || exit 1
fi

# Figure out whether this is a single-host build, in which
# case we just obey the options, or a multi-host build, in
# which case we do some stuff on this platform (already done
# above), and then launch off a build on the other platform,
# and make sure we only build the docs on linux.

if [ $# -ge 1 ]; then
  for host in $@; do
    ssh -n $host "cd `pwd`/../..; $0 -p $avoid -D -c $TAG" &
  done
fi

eval `scram runtime -sh`
$dobuild && scram b release-reset-arch && scram b release-build
$dotests && scram b release-check
$dodocs && scram b release-docs

# Wait for all builds to finish
wait

# Clean up and protect directories
$dochmod && scram b release-freeze
